### Retorna Todos os Pokemons
GET http://localhost:3003/pokemon
Content-Type: application/json
### Retorna Pokemons por nome
GET http://localhost:3003/name 
Content-Type: application/json

{
"name": "pikachu"
}

### Retorna pokemon por paginas
GET http://localhost:3003/pages
Content-Type: application/json

{
    "offset": 2
}
### Retorna pokemon por tipo
GET http://localhost:3003/type 
Content-Type: application/json

{
    "type":"WATER"
}
### Retorna pokemon pelos tipos
GET http://localhost:3003/pokemon/types
Content-Type: application/json

{
    "type1": "BUG", 
    "type2": "POISON",
    "offset" : 1
}